In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import zipfile

with zipfile.ZipFile('/content/drive/MyDrive/archive (2).zip', 'r') as zip_ref:
    zip_ref.extractall('/content/archive (2)')

In [3]:
import pandas as pd
df=pd.read_csv("/content/archive (2)/data.csv")
df.head()

,image,description,display name,category
0,3238.jpg,"Round toed, black sports shoes with red accent...",Puma Men Black 65CC Lo Ducati Sports Shoes,Sports Shoes
1,43044.jpg,Style Note Built with the breathability and ze...,Nike Men Charcoal Grey Shorts,Shorts
2,54018.jpg,Teal handbag that has stitch detailing with a...,Kiara Women Teal Handbag,Handbags
3,8141.jpg,"Perfectly stylish, this fastrack analog wrist ...",Fastrack Women Freestyle Sports Analog Steel B...,Watches
4,22245.jpg,These id mid-top chukka shoes add a fresh spin...,ID Men Brown Casual Shoes,Casual Shoes

In [4]:
a=df['category'].value_counts()
a

category
Tshirts                7069
Shirts                 3215
Casual Shoes           2846
Watches                2542
Sports Shoes           2036
                       ...
Cushion Covers            1
Hair Accessory            1
Body Wash and Scrub       1
Mens Grooming Kit         1
Shoe Laces                1
Name: count, Length: 142, dtype: int64

In [5]:
counts = df['category'].value_counts()
counts[counts > 500]

category
Tshirts                  7069
Shirts                   3215
Casual Shoes             2846
Watches                  2542
Sports Shoes             2036
Kurtas                   1844
Tops                     1762
Handbags                 1759
Heels                    1323
Sunglasses               1073
Wallets                   936
Flip Flops                916
Sandals                   897
Briefs                    849
Belts                     813
Backpacks                 724
Socks                     686
Formal Shoes              637
Perfume and Body Mist     614
Jeans                     608
Shorts                    547
Trousers                  530
Name: count, dtype: int64

In [6]:
valid_categories = counts[counts > 500].index
df_filtered = df[df['category'].isin(valid_categories)]
df_filtered['category'].value_counts()

category
Tshirts                  7069
Shirts                   3215
Casual Shoes             2846
Watches                  2542
Sports Shoes             2036
Kurtas                   1844
Tops                     1762
Handbags                 1759
Heels                    1323
Sunglasses               1073
Wallets                   936
Flip Flops                916
Sandals                   897
Briefs                    849
Belts                     813
Backpacks                 724
Socks                     686
Formal Shoes              637
Perfume and Body Mist     614
Jeans                     608
Shorts                    547
Trousers                  530
Name: count, dtype: int64

In [7]:
#downsampling data to 530 images in each category
balanced_df = (
    df_filtered
    .groupby('category', group_keys=False)
    .apply(lambda x: x.sample(n=530, random_state=42))
)

/tmp/ipykernel_343/339973060.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(n=530, random_state=42))

In [8]:
balanced_df.shape

(11660, 4)

In [9]:
#shuffliing dataset
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [10]:
balanced_df.head()

,image,description,display name,category
0,56882.jpg,"Heel: 2.5"" Open toe heels with a forefoot and ...",HM Women Red Heels,Heels
1,33647.jpg,The luxe comfort and rugged styling of lotto's...,Lotto Men Ridge Black Sandals,Sandals
2,41513.jpg,Style Note Wear these fashion forward and tren...,Basics Men Aviator Sunglasses 10BSG24309,Sunglasses
3,42865.jpg,Style Note This french connection piece nails ...,French Connection Women Black Dorris Handbag,Handbags
4,19797.jpg,"Composition Grey polo t-shirt with red,blue an...",U.S. Polo Assn. Men Striped Grey T-shirt,Tshirts

In [11]:
#splitting the dataset now
from sklearn.model_selection import train_test_split

#making train 80% and test 20%
train_df, temp_df = train_test_split(
    balanced_df,
    test_size=0.2,
    stratify=balanced_df['category'],
    random_state=42
)
#making validation from test set
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,
    stratify=temp_df['category'],
    random_state=42
)

In [12]:
print(len(train_df))
print(len(val_df))
print(len(test_df))

9328
1166
1166

In [13]:
train_df['category'].value_counts()
#to check every count

category
Tshirts                  424
Sports Shoes             424
Jeans                    424
Trousers                 424
Wallets                  424
Handbags                 424
Tops                     424
Sandals                  424
Briefs                   424
Flip Flops               424
Heels                    424
Casual Shoes             424
Perfume and Body Mist    424
Socks                    424
Formal Shoes             424
Sunglasses               424
Backpacks                424
Shirts                   424
Kurtas                   424
Watches                  424
Belts                    424
Shorts                   424
Name: count, dtype: int64